//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booksite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Book_name { get; set; }
        public string Book_image { get; set; }
        [Required]
        public string Description { get; set; }
        public Nullable<int> Category_name { get; set; }
        public Nullable<int> Publisher_name { get; set; }
        public Nullable<int> Author_name { get; set; }
        public Nullable<int> Supplier_name { get; set; }
        public Nullable<int> Original_Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Sale_price { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
