//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booksite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Check_out
    {
        public int ID { get; set; }
        [Required]
        public int Account_name { get; set; }
        [Required]
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> Cart_total { get; set; }
        public string Voucher { get; set; }
        public Nullable<int> Shipping_fee { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual Shipping_fee Shipping_fee1 { get; set; }
    }
}
